SELECT 'YOUNGEST' AS TYPE, NAME, BIRTHDAY
FROM employees
WHERE BIRTHDAY = (
    SELECT MIN(BIRTHDAY)
    FROM employees
)
UNION ALL
SELECT 'OLDEST' AS TYPE, NAME, BIRTHDAY
FROM employees
WHERE BIRTHDAY = (
    SELECT MAX(BIRTHDAY)
    FROM employees
);